module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#c6f34c",
        "surface": "#f7fbef",
        "on-tertiary-fixed-variant": "#41493f",
        "inverse-surface": "#2d322a",
        "on-tertiary-fixed": "#161d16",
        "tertiary-fixed-dim": "#c1c9bc",
        "surface-container": "#ebf0e4",
        "on-surface-variant": "#40493c",
        "on-primary-fixed": "#002200",
        "background": "#f7fbef",
        "surface-container-low": "#f1f5e9",
        "primary-fixed": "#a3f78d",
        "surface-container-high": "#e5eade",
        "primary-fixed-dim": "#87da74",
        "on-secondary-container": "#536d00",
        "on-error": "#ffffff",
        "surface-bright": "#f7fbef",
        "surface-tint": "#1c6d14",
        "surface-variant": "#dfe4d8",
        "inverse-on-surface": "#eef2e6",
        "on-background": "#181d16",
        "on-surface": "#181d16",
        "on-primary": "#ffffff",
        "primary": "#004100",
        "on-secondary-fixed-variant": "#3a4d00",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#005300",
        "error-container": "#ffdad6",
        "surface-dim": "#d7dcd0",
        "on-tertiary-container": "#bac2b5",
        "tertiary": "#323930",
        "tertiary-fixed": "#dde5d8",
        "secondary": "#4e6700",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "outline-variant": "#c0cab8",
        "outline": "#707a6b",
        "secondary-fixed-dim": "#aad630",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#151f00",
        "on-primary-container": "#80d26d",
        "primary-container": "#005b00",
        "surface-container-highest": "#dfe4d8",
        "tertiary-container": "#485046",
        "secondary-container": "#c6f34c",
        "inverse-primary": "#87da74"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "16px",
        "base": "4px",
        "gutter": "16px",
        "md": "24px",
        "container-padding": "24px",
        "lg": "32px",
        "xs": "8px",
        "xl": "48px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "label-xs": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-metrics": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "label-xs": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-metrics": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
