-- V3__create_admin_schema.sql
-- Tables for GreenMove Admin Control Center: app_users, fuel_prices, emission_factors, audit_logs

CREATE TABLE app_users (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    joined_date VARCHAR(50),
    last_active VARCHAR(50)
);

CREATE TABLE fuel_prices (
    id VARCHAR(100) PRIMARY KEY,
    fuel_type VARCHAR(100) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    unit VARCHAR(50) NOT NULL,
    source VARCHAR(255) NOT NULL,
    updated_at VARCHAR(100),
    updated_by VARCHAR(100)
);

CREATE TABLE emission_factors (
    id VARCHAR(100) PRIMARY KEY,
    category VARCHAR(100) NOT NULL,
    factor DOUBLE PRECISION NOT NULL,
    unit VARCHAR(50) NOT NULL,
    source VARCHAR(255) NOT NULL,
    updated_at VARCHAR(100),
    updated_by VARCHAR(100)
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp VARCHAR(100) NOT NULL,
    actor VARCHAR(100) NOT NULL,
    action VARCHAR(255) NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    details TEXT NOT NULL,
    result VARCHAR(50) NOT NULL
);

CREATE INDEX idx_users_email ON app_users (email);
CREATE INDEX idx_audit_logs_timestamp ON audit_logs (timestamp);
